#!/bin/bash

cd $(dirname $0)/..
TAG=${BUILD_NUMBER:-"latest"}
./scripts/bootstrap

pushd nginx
docker build --rm -t rancheriodhci/demo-nginx:${TAG} .
popd
pushd web
docker build --rm -t rancheriodhci/demo-web:${TAG} .
